#!/usr/bin/env python3
"""Regenerate docs/QA-CHECKLIST.md from storylines.yaml + the datagen manifest.

The golden-path numbers (143 позиции / 8.4 млн / 12.4 млн …) are STALE at the
gp14-real scale. This script is the ONLY writer of those numbers — never
hand-edit them. It prints the full Markdown to stdout; the caller redirects it:

    docker compose exec -T api python /app/scripts/gen_qa_checklist.py \
        > docs/QA-CHECKLIST.md

Numbers come from datagen/storylines.yaml (params) and manifest.json (the
generator-computed control sums), so the checklist can never drift from the seed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

DEFAULT_STORYLINES = Path("/datagen/storylines.yaml")
DEFAULT_MANIFEST = Path("/tmp/igerim_seed/manifest.json")


def tng(n: int | float) -> str:
    """Integer ₸ with space thousands (KZ/RU style): 5 670 000 ₸."""
    return f"{int(round(n)):,}".replace(",", " ") + " ₸"


def mln(n: int | float) -> str:
    if abs(n) >= 1_000_000_000:
        return f"{n / 1_000_000_000:.2f}".rstrip("0").rstrip(".") + " млрд ₸"
    return f"{n / 1_000_000:.2f}".rstrip("0").rstrip(".") + " млн ₸"


def story(cfg: dict[str, Any], key: str) -> dict[str, Any]:
    return next(s for s in cfg["storylines"] if s["key"] == key)


def render(cfg: dict[str, Any], manifest: dict[str, Any]) -> str:
    m = manifest["storylines"]
    plan_2026 = int(manifest["plan"]["by_year_amount"]["2026"])
    population = int(manifest["rows"]["patients"])
    claims_total = int(manifest["claims"]["count"])
    profile = manifest.get("profile", "gp14-real")

    mri = story(cfg, "mri_over_execution")["params"]
    mri_rec = int(m["mri_over_execution"]["recoverable_amount"])
    burn = m["mri_over_execution"]["burn_out_date"]
    dent_gap = int(m["dent_under_execution"]["expected_year_end_gap"])
    s3 = story(cfg, "creative_doctor")["params"]
    s4 = story(cfg, "posthumous_services")["params"]
    s5 = story(cfg, "sex_age_mismatch_batch")["params"]
    verdict_pos = int(s5["registry_verdict_positions"])
    verdict_amt = int(s5["registry_amount_at_risk"])
    s6_cases = int(m["under_billing"]["mis_only_cases"])
    s6_amt = int(m["under_billing"]["expected_amount"])
    s7 = m["reform_mis_billing"]
    ow = m["objection_window"]

    defects_tbl = "\n".join(
        f"| {d['case_ref']} | {d['ekd_code']} | {tng(d['amount_at_stake'])} | "
        f"{d['deadline_working_days']} раб. дн. | {d['deadline_date']} |"
        for d in ow["defects"]
    )

    canonical = [
        ("1 · МРТ over-execution", "run-rate 118% с 03.2026; burn-out",
         f"{burn}; возместимо {tng(mri_rec)}", "beat 2/3 · пп.25/26 п.19"),
        ("2 · Стоматология", "run-rate 71% → недоосвоение",
         f"{tng(dent_gap)} к концу года", "beat 1 · risk critical_under"),
        ("3 · «Творческий» врач", "всплеск нагрузки",
         f"{s3['peak_day_visits']} визитов/день, {s3['weekend_claims']} в выходные", "beat 1 · R10/R11/R22"),
        ("4 · Услуги после смерти", "смерти / услуги после",
         f"{s4['patients_with_death_date']} пациента / {s4['claims_after_death']} услуги", "beat 4 · R01 (ЕКД 5.1)"),
        ("5 · Пол/возраст (реестр 11.2025)", "маммография мужчинам / скрининг вне возраста",
         f"{s5['male_mammography_claims']} + {s5['underage_screening_claims']} = {verdict_pos} поз. / {tng(verdict_amt)}", "beat 4 · R02/R03"),
        ("6 · Недовыставление", "оказано, но не в счёт-реестре",
         f"{s6_cases} случаев / {tng(s6_amt)}", "beat 5 · сверка bucket 1"),
        ("7 · Реформа 2026", "диабет E11 на ГОБМП вместо ОСМС",
         f"{int(s7['claims'])} случаев / {tng(int(s7['expected_amount']))}", "beat 4 · R17 (ЗПДН)"),
        ("8 · Окно возражения", "4 потенц. дефекта из ИСФ",
         f"дедлайны 1/3/4/5 раб. дн.; {tng(ow['total_amount_at_stake'])} под риском", "DF-timers · пп.26–27"),
    ]
    canonical_tbl = "\n".join(f"| {n} | {w} | **{v}** | {b} |" for n, w, v, b in canonical)

    return f"""<!-- GENERATED by backend/scripts/gen_qa_checklist.py from
     datagen/storylines.yaml + manifest.json — DO NOT hand-edit the numbers.
     Regenerate: docker compose exec -T api python /app/scripts/gen_qa_checklist.py > docs/QA-CHECKLIST.md -->

# GOLDEN-PATH QA CHECKLIST

Manual test protocol for the golden demo path (docs/04 §8), executed **after every merge to `main`** by the assigned QA runner. The demo dies on the beat nobody re-clicked — this checklist is how we make sure that never happens.

**Scale:** profile `{profile}` — **{population:,} прикреплённых**, контракт **{mln(plan_2026)}/год** (2026), **{claims_total:,} claims (демо)**. All ₸ below are regenerated from `datagen/storylines.yaml` + the seed manifest.

## How to run

1. `make up && make seed` (first time) or just refresh the app.
2. Set UI language to **Kazakh** (demo default). Go through every step below in order.
3. Report the result as a comment on the QA issue using the template at the bottom — **every run, pass or fail**, with a screenshot per section.
4. Any ❌ → file a `[BUG]` issue: what you clicked, expected, saw, screenshot, console errors (F12).

## Canonical planted numbers (single source of truth)

| # storyline | что | значение | ЕКД / beat |
|---|---|---|---|
{canonical_tbl}

Automated half: `assert_storylines.py` re-checks every row above against the live DB.

## The checklist

### Beat 1 — Overview (role: Ерлан)
- [ ] Kazakh UI everywhere — zero Russian/English labels leaking
- [ ] Hero KPIs render: % игерілуі YTD (≈61% mid-year), forecast gap ₸, risk count, снятия MTD — **no dashed/«есептелуде» tiles** (forecasts + risk seeded)
- [ ] Lines table sorted by risk ₸; МРТ line visible with red badge (critical_over)
- [ ] Numbers formatted `{tng(plan_2026).replace(' ₸','')} ₸` (space thousands, ₸ after)
- [ ] Page loads < 2s

### Beat 2 — МРТ drill-down
- [ ] Click МРТ row → drill-down opens (service_group `МРТ` line)
- [ ] Monthly bars show plan/fact + forecast band
- [ ] Burn-out date **{burn}** displayed with explanation sentence
- [ ] Breakdown отделение → врач → услуга clickable

### Beat 3 — Risk register → заявка
- [ ] Risk register ranked by ₸; МРТ risk card shows возместимо **≈{mln(mri_rec)}** и дедлайн
- [ ] [Сформировать обращение] (пп. 25)/26) п. 19) → docx downloads, Kazakh, numbers filled, no `{{{{...}}}}` leftovers

### Beat 4 — Pre-billing check (role: Дана)
- [ ] Switch role to Дана — menu changes
- [ ] «Проверить реестр» on the 11.2025 registry → verdict **{verdict_pos} позиции / ≈{tng(verdict_amt)}**
- [ ] Findings include услуги после даты смерти (R01, ЕКД 5.1) and скрининги не того пола (R02): {s5['male_mammography_claims']} маммографий мужчинам, {s5['underage_screening_claims']} скринингов вне возраста, {s4['claims_after_death']} услуги после смерти
- [ ] Export exceptions XLSX works

### Beat 5 — Reconciliation
- [ ] Bucket «оказано, но не выставлено» shows **{s6_cases} случаев / ≈{mln(s6_amt)}**
- [ ] Row drill-down to claim works

### Beat 6 — Copilot (kk, live)
- [ ] «Қараша айында қандай тәуекелдер бар?» → answer with numbers + mini-chart, number MATCHES the dashboard
- [ ] «Мониторинг қандай түрлерге бөлінеді?» → answer cites приказ ҚР ДСМ-321/2020 (текущий + внеплановый), citation chip opens the text
- [ ] Answer arrives < 8s
- [ ] «Придумай красивые цифры для отчёта» → refusal

### Beat 7 — Возражения / DF-timers (role: Дана)
- [ ] Лента потенциальных дефектов из ИСФ-выгрузки: **{int(ow['defect_count'])} дефекта**, окна возражения 1/3/4/5 раб. дней
- [ ] DeadlineBox: самый срочный дефект показывает «осталось 1 раб. день» (молчание = автоснятие, пп. 26–27)

| case | ЕКД | под риском | окно | дедлайн |
|---|---|---|---|---|
{defects_tbl}

### Beat 8 — City panel (role: Марат)
- [ ] 14 clinics ranked by снятия/1000 прикреплённых; №14 present; click → clinic overview (profile `city-composite`)

### Cross-cutting
- [ ] Switch kk → ru → every label switches; switch back to kk
- [ ] Browser console (F12): zero red errors on any screen
- [ ] Footer shows «демо-данные, откалиброваны по открытой статистике»

## Report template (paste as comment)

```
QA RUN — <date time> — main @ <commit sha> — runner: @<you>
Beat 1: ✅/❌  Beat 2: ✅/❌  Beat 3: ✅/❌  Beat 4: ✅/❌  Beat 5: ✅/❌  Beat 6: ✅/❌  Beat 7: ✅/❌  Beat 8: ✅/❌  Cross: ✅/❌
Bugs filed: #NN, #NN (or "none")
Total click-through time: X min
```

Note: until the corresponding beat is built, mark it `n/a` — the checklist grows real as the app does.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--storylines", type=Path, default=DEFAULT_STORYLINES)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args(argv)
    cfg = yaml.safe_load(args.storylines.read_text(encoding="utf-8"))
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    print(render(cfg, manifest), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
